###

POST http://localhost:3000/api/generateLease HTTP/1.1
# content-type: application/json

{
    "tenantName": "aaa",
    "lessorName": "bbb"
}
###

POST http://localhost:3000/api/xxx HTTP/1.1
# content-type: application/json

{
    "tenantName": "ccc",
    "lessorName": "ddd"
}