import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'

import { cn } from '@/lib/utils'
const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

const inter = FontSans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  // return (
  //   <html lang='en'>
  //     <body className={inter.className}>{children}</body>
  //   </html>
  // )
  return (
    <html lang='en' suppressHydrationWarning>
      <head />
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}

// import '@/styles/globals.css'
// import { Inter as FontSans } from 'next/font/google'

// import { cn } from '@/lib/utils'

// const fontSans = FontSans({
//   subsets: ['latin'],
//   variable: '--font-sans'
// })

// export default function RootLayout({ children }: RootLayoutProps) {
//   return (
//     <html lang='en' suppressHydrationWarning>
//       <head />
//       <body
//         className={cn(
//           'min-h-screen bg-background font-sans antialiased',
//           fontSans.variable
//         )}
//       >
//         ...
//       </body>
//     </html>
//   )
// }
